// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJxc7nPXAP90AhkcSicWaFODwybTSzoFE',
    appId: '1:405759057323:web:36106734dd2242970e46ee',
    messagingSenderId: '405759057323',
    projectId: 'ehliyet-cd485',
    authDomain: 'ehliyet-cd485.firebaseapp.com',
    storageBucket: 'ehliyet-cd485.firebasestorage.app',
    measurementId: 'G-LPTZH913Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyK8X5G6OWBHJunSGjixKXuwqK9ySZYgY',
    appId: '1:405759057323:android:f56c49d879c190c90e46ee',
    messagingSenderId: '405759057323',
    projectId: 'ehliyet-cd485',
    storageBucket: 'ehliyet-cd485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmv2BVOcy0jezYx_Tk1yyubq3xemQQ-BM',
    appId: '1:405759057323:ios:90dc35b7a9de721e0e46ee',
    messagingSenderId: '405759057323',
    projectId: 'ehliyet-cd485',
    storageBucket: 'ehliyet-cd485.firebasestorage.app',
    iosBundleId: 'com.example.ehliyet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmv2BVOcy0jezYx_Tk1yyubq3xemQQ-BM',
    appId: '1:405759057323:ios:90dc35b7a9de721e0e46ee',
    messagingSenderId: '405759057323',
    projectId: 'ehliyet-cd485',
    storageBucket: 'ehliyet-cd485.firebasestorage.app',
    iosBundleId: 'com.example.ehliyet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJxc7nPXAP90AhkcSicWaFODwybTSzoFE',
    appId: '1:405759057323:web:71b81a6eee89bac30e46ee',
    messagingSenderId: '405759057323',
    projectId: 'ehliyet-cd485',
    authDomain: 'ehliyet-cd485.firebaseapp.com',
    storageBucket: 'ehliyet-cd485.firebasestorage.app',
    measurementId: 'G-2ZJGDHT420',
  );
}
